services:
  dbservice:
    container_name: parkingdb
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: parking
      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - /caminho/local/para/volume:/var/lib/mysql