spring:
  application:
    name: parking
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:parking}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
#  sql:
#    init:
#      schema-locations: classpath:sql/jobportal-schema.sql
#      data-locations: classpath:sql/jobportal-data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
  docker:
    compose:
      stop:
        command: down
server:
  port: 3003